WIP
obot-platform/obot pull request #1085
Opened 2024-12-31 18:56 UTC by g-linville

2025-01-16 19:01 UTC, ivyjeong13 commented on ui/admin/app/components/auth-and-model-providers/ProviderForm.tsx
> +				onSuccess();
> There is a known bug in the frontend where you have to refresh the page after configuring the auth provider in order to see the change. It's taken me long enough to get this PR ready, so I figured it would be best to fix that in a follow up (or have Ryan or Ivy figure it out for me, lol).

My initial guess is you may need to add `mutate(AuthProviderApiService.getAuthProviders.key())` here! That should get auth providers updated after a successful configure.

2025-01-16 19:21 UTC, ivyjeong13 commented on ui/admin/app/components/auth-and-model-providers/ProviderForm.tsx
> +export function ProviderForm({
nit: Wondering we could break the model provider / auth provider logic into a parent component and pass that in as props to ProviderForm, ProviderConfigure, ProviderDeconfigure. 

Thinking something like: 
```
// called in auth_providers.tsx specific context
<ProviderForm
    onConfigure={configureAuthProvider}
    loading={configureAuthProvider.isLoading || isLoading}
    tooltips={AuthProviderRequiredTooltips}
/>

// called in model_providers.tsx specific context
<ProviderForm
    onConfigure={configureModelProvider}
    loading={configureModelProvider.isLoading || isLoading}
    tooltips={ModelProviderRequiredTooltips}
/>
```

Then when you have to call them, you're not worried about handling the other provider type cases (or if something else uses this in the future).

2025-01-16 19:27 UTC, g-linville commented on ui/admin/app/components/auth-and-model-providers/ProviderForm.tsx
> +				onSuccess();
Thanks, this worked!

2025-01-16 19:51 UTC, g-linville commented on ui/admin/app/components/auth-and-model-providers/ProviderForm.tsx
> +export function ProviderForm({
If it's alright, I'd like for this to be in a follow-up.

2025-01-16 21:47 UTC, ryanhopperlowe commented
<img width="1839" alt="Screenshot 2025-01-16 at 3 47 00 PM" src="https://github.com/user-attachments/assets/b3a27bba-7048-4cfc-a2c1-a6cd52cae0b6" />

I'm being prompted to setup an auth provider, but I don't see any to pick from

2025-01-16 21:49 UTC, ryanhopperlowe commented on ui/admin/app/components/auth-and-model-providers/Bootstrap.tsx
> +	};
Let's Create a `BootstrapService` for all of these

2025-01-16 22:37 UTC, ryanhopperlowe commented on ui/admin/app/components/auth-and-model-providers/ProviderDeconfigure.tsx
> +function warningMessage(t: string | undefined): string | undefined {
nit: 

```suggestion
function warningMessage(t?: string) {
```

2025-01-16 22:41 UTC, ryanhopperlowe commented on ui/admin/app/components/auth-and-model-providers/ProviderIcon.tsx
> +					provider.id !== CommonAuthProviderIds.GITHUB,
```suggestion
					![CommonModelProviderIds.AZURE_OPENAI, CommonAuthProviderIds.GOOGLE, CommonAuthProviderIds.GITHUB].includes(provider.id)
```

2025-01-16 23:12 UTC, ryanhopperlowe commented on ui/admin/app/lib/model/providers.ts
>  };
These should follow a more True-to-life pattern:

```ts

type ProviderBase = {...}

type ModelProviderBase = ProviderBase & {...}
type ModelProvider = EntityMeta & ProviderBase & { type: 'modelprovider' }

type AuthProviderBase = ProviderBase & {...}
type AuthProvider = EntityMeta & AuthProviderBase & { type: 'authprovider' }

type Provider = ModelProvider | AuthProvider
```

2025-01-16 23:17 UTC, ryanhopperlowe commented on ui/admin/app/routes/_auth.tsx
> +			[401, 403].includes(error.response?.status ?? 0):
@g-linville can you explain why you needed to add this? I'd like to make sure our first layer of error handling can catch this and convert it to the proper error type

2025-01-17 01:17 UTC, g-linville commented
@ryanhopperlowe you need to download and build my branch of the tools repo from this PR: https://github.com/obot-platform/tools/pull/320

And then set the `OBOT_SERVER_TOOL_REGISTRY` environment variable to point to your local copy of it when you run `make dev`. This will make the auth providers show up.

2025-01-17 01:18 UTC, g-linville commented on ui/admin/app/components/auth-and-model-providers/Bootstrap.tsx
> +	};
Sounds good. If it's okay, I'd like for that to be a follow-up refinement. For this PR, the UI just needs to work. Non-optimal things about the code can be fixed afterward.

2025-01-17 01:20 UTC, g-linville commented on ui/admin/app/lib/model/providers.ts
>  };
I'd like for this to be a follow-up improvement.

2025-01-17 01:20 UTC, g-linville commented on ui/admin/app/routes/_auth.tsx
> +			[401, 403].includes(error.response?.status ?? 0):
I don't 100% remember but I think it had to do with the error we get back when we hit `/api/me` with my new changes to the backend.

2025-01-17 01:21 UTC, g-linville commented on ui/admin/app/components/auth-and-model-providers/ProviderIcon.tsx
> +					provider.id !== CommonAuthProviderIds.GITHUB,
Fixed

2025-01-17 01:21 UTC, g-linville commented on ui/admin/app/components/auth-and-model-providers/ProviderDeconfigure.tsx
> +function warningMessage(t: string | undefined): string | undefined {
Fixed

2025-01-17 02:17 UTC, g-linville commented
Sorry for force pushing again. There were more conflicts that I needed to fix.

2025-01-17 03:07 UTC, njhale approved these changes
Some nits and suggestions, nothing that should hold this up.

2025-01-17 03:07 UTC, njhale commented on pkg/accesstoken/accesstoken.go
> +}
nit: compiler optimizations aside, you can avoid extra allocations by creating the key object once, up front:

```go
package accesstoken

import "context"

var accessTokenKey = struct{}{}

func ContextWithAccessToken(ctx context.Context, accessToken string) context.Context {
	return context.WithValue(ctx, accessTokenKey, accessToken)
}

func GetAccessToken(ctx context.Context) string {
	accessToken, _ := ctx.Value(accessTokenKey).(string)
	return accessToken
}
```

2025-01-17 03:07 UTC, njhale commented on pkg/api/handlers/authprovider.go
> +	}
If the env hasn't changed this will still delete and recreate the credential and stop the provider even the env hasn't changed, right? Would it be better to check for changes to the credential first?

2025-01-17 03:07 UTC, njhale commented on pkg/gateway/server/oauth.go
>  	}
Could you just `Get` the ToolReference for the specific auth provider by name and check if it's configured (and that it's an authprovider type tool)?. Would result in way fewer operations IIUC.

2025-01-17 03:15 UTC, njhale commented
> ... And then set the OBOT_SERVER_TOOL_REGISTRY environment variable to point to your local copy of it when you run make dev. This will make the auth providers show up.

@g-linville @ryanhopperlowe this has recently changed due to https://github.com/obot-platform/obot/pull/1193 merging.

Now, instead of setting `OBOT_SERVER_TOOL_REGISTRY`, you'll need set the `GPTSCRIPT_TOOL_REMAP` environment variable; e.g.

```
export GPTSCRIPT_TOOL_REMAP='github.com/obot-platform/tools=/Users/nick/projects/obot-platform/tools'
```

2025-01-17 03:21 UTC, njhale commented on pkg/accesstoken/accesstoken.go
> +}
We can refine this whenever.

2025-01-17 03:21 UTC, njhale commented on pkg/gateway/server/oauth.go
>  	}
We can refine this later.

2025-01-17 15:03 UTC, g-linville commented on pkg/api/handlers/authprovider.go
> +	}
All I did here was copy the logic that we used for auth providers. I think @thedadams may have been the one who implemented that, and would know the answer to this.

2025-01-17 15:04 UTC, g-linville commented
@njhale @ryanhopperlowe for testing with this branch, the old env var should be used to set the registry, since I have not (yet) brought in those changes from main to this branch.

2025-01-17 17:54 UTC, StrongMonkey commented on pkg/api/handlers/authprovider.go
> +			fmt.Printf("revealing creds for auth provider %q\n", ref.Name)
Nit: this is debug log? if not should we use our standard log library to print?

2025-01-17 17:54 UTC, StrongMonkey commented on pkg/api/handlers/authprovider.go
> +	fmt.Printf("revealing creds for auth provider %q\n", ref.Name)
Debug log

2025-01-17 17:54 UTC, StrongMonkey commented on pkg/bootstrap/bootstrap.go
> +		fmt.Printf("Bootstrap token: %s\n", token)
Do we print it so that user can grab it from the log? if so I would suggest the log to be more descriptive.

2025-01-17 18:30 UTC, g-linville commented on pkg/api/handlers/authprovider.go
> +			fmt.Printf("revealing creds for auth provider %q\n", ref.Name)
Thanks for finding these! I forgot to remove them before. Pushed the fix

2025-01-17 18:30 UTC, g-linville commented on pkg/api/handlers/authprovider.go
> +	fmt.Printf("revealing creds for auth provider %q\n", ref.Name)
Fixed

2025-01-17 18:30 UTC, g-linville commented on pkg/bootstrap/bootstrap.go
> +		fmt.Printf("Bootstrap token: %s\n", token)
Fixed

2025-01-20 14:30 UTC, g-linville commented
Rebased again to fix conflicts.

2025-01-20 18:00 UTC, thedadams requested changes

2025-01-20 18:00 UTC, thedadams commented on apiclient/types/authprovider.go
> +	Namespace     string `json:"namespace"`
This shouldn't be part of the manifest.

2025-01-20 18:00 UTC, thedadams commented on pkg/api/router/router.go
> +
nit: remove line

2025-01-20 18:00 UTC, thedadams commented on pkg/api/server/server.go
> +			if !s.authorizer.Authorize(req, user) {
This if-statement should not be nested.

2025-01-20 18:00 UTC, thedadams commented on pkg/bootstrap/bootstrap.go
> +func (b *Bootstrap) Logout(req api.Context) error {
Can we delete the `bootstrap` user from the database in this case? If it doesn't make sense to do here, can we do it at some point?

2025-01-20 18:00 UTC, thedadams commented on pkg/gateway/server/dispatcher/dispatcher.go
> +	modelLock  *sync.RWMutex
nit: the dispatcher can be separated from the "transformer" and the dispatcher made generic with the implementation used for both model and auth providers.

2025-01-20 18:00 UTC, thedadams commented on pkg/gateway/server/dispatcher/dispatcher.go
> +	// Ensure that the auth provider has been configured so that we don't get stuck waiting on a prompt.
Can we use the `isAuthProviderConfigured` method here?

2025-01-20 18:00 UTC, thedadams commented on pkg/gateway/server/tokenreview.go
> +		namespace = fmt.Sprint(tkn.AuthProviderNamespace)
Is it necessary to use `fmt.Sprintf` here?

2025-01-20 18:00 UTC, thedadams commented on pkg/proxy/proxy.go
> +			http.Error(w, "no auth providers configured", http.StatusInternalServerError)
Should this be a bad request?

2025-01-20 18:00 UTC, thedadams commented on pkg/proxy/proxy.go
> +	for k, v := range req.Header {
sr.Header = req.Header

2025-01-20 18:00 UTC, thedadams commented on pkg/services/config.go
> +	DisableAuthentication      bool     `usage:"Disable authentication" default:"false" env:"OBOT_DISABLE_AUTHENTICATION"`
If one were to use this as a CLI flag, using `--disable-authentication` seems that it would actually enable authentication.

2025-01-20 18:00 UTC, thedadams commented on pkg/services/config.go
> +	NoReplyEmailAddress        string   `usage:"The email to use for no-reply emails from obot"`
Is this related to your changes?

2025-01-20 18:00 UTC, thedadams commented on pkg/services/config.go
> +	bootstrap2 "github.com/obot-platform/obot/pkg/bootstrap"
nit: I don't think this import needs to be renamed.

2025-01-20 18:05 UTC, g-linville commented on apiclient/types/authprovider.go
> +	Namespace     string `json:"namespace"`
Are you sure? `Name` is part of the ModelProviderManifest. We need a namespace for auth providers, since I was told I can't assume that they will always be in `default`.

2025-01-20 18:06 UTC, g-linville commented on pkg/api/server/server.go
> +			if !s.authorizer.Authorize(req, user) {
If we bring it outside of `if strings.HasPrefix(req.URL.Path, "/api/")`, then we end up deny all unauthenticated requests to the user UI, which basically breaks everything. It needs to be nested in here.

2025-01-20 18:07 UTC, g-linville commented on pkg/bootstrap/bootstrap.go
> +func (b *Bootstrap) Logout(req api.Context) error {
I'm okay with doing this, but I'm not sure that it's really necessary?

2025-01-20 18:12 UTC, g-linville commented on pkg/gateway/server/tokenreview.go
> +		namespace = fmt.Sprint(tkn.AuthProviderNamespace)
Oh, probably not.

2025-01-20 18:12 UTC, g-linville commented on pkg/proxy/proxy.go
> +			http.Error(w, "no auth providers configured", http.StatusInternalServerError)
yeah

2025-01-20 18:13 UTC, g-linville commented on pkg/services/config.go
> +	DisableAuthentication      bool     `usage:"Disable authentication" default:"false" env:"OBOT_DISABLE_AUTHENTICATION"`
Good point. I'll invert this

2025-01-20 18:13 UTC, g-linville commented on pkg/services/config.go
> +	NoReplyEmailAddress        string   `usage:"The email to use for no-reply emails from obot"`
Nope. Might have been an accident when trying to resolve conflicts. Maybe this got added and removed at some point? I can take it away.

2025-01-20 18:19 UTC, g-linville commented on pkg/gateway/server/dispatcher/dispatcher.go
> +	modelLock  *sync.RWMutex
I'd like for this to be a later change if it is needed.

2025-01-20 18:31 UTC, thedadams commented on pkg/api/server/server.go
> +			if !s.authorizer.Authorize(req, user) {
If that is the case, then that should be fixed outside of this. This definitely should not be nested.

2025-01-20 18:31 UTC, thedadams commented on pkg/gateway/server/dispatcher/dispatcher.go
> +	modelLock  *sync.RWMutex
I agree. Which is why it is a nit.

2025-01-20 23:09 UTC, thedadams approved these changes

2025-01-20 23:09 UTC, merged